### ISSUE TITLE
StatTag does not work in footnotes

### ISSUE THREAD

**Issue by mronkko** [StatTag/StatTagMac#6]
I am using Word for Mac. After inserting a tag in a footnote and trying to update the tag, the progress dialog appears and disappears after a while but the tag value is not updated. The attached files demonstrate the issue.
[Archive.zip](https://github.com/StatTag/StatTagMac/files/4856476/Archive.zip)

**Comment by lrasmus** [comment]
@mronkko - you've got us on that one.   We did not include support for footnotes, expecting that "nobody would ever want that" (always famous last words).  Let me discuss with the team, and see if this is something we can consider adding.  Thanks!

**Comment by lrasmus** [comment]
This gets even better!  Turns out this was something that was already working in the Windows version, and so we definitely should include in macOS build to be consistent.

It looks like the Word API acts differently in macOS compared to Windows, and so this implementation will specifically just work on the main document text, footnotes, and endnotes (for now).  We can extend to other document parts as needed later.  The decision to not do everything is so that we don't add a lot of extra processing time each time we update tags.

**Comment by lrasmus** [comment]
Released in 3.0.6 - available from https://stattag-registration.fsm.northwestern.edu/

Thanks again @mronkko for reporting!
